name: Execute price prediction
on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *'
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: true
jobs:
  build:
    name: run script
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repository
        uses: actions/checkout@v3

      # - name: Set up Python
      #   uses: actions/setup-python@v2
      #   with:
      #     python-version: '3.8'

      # - name: Install pipenv
      #   run: pip install poetry

      - name: Cache Poetry
        uses: actions/cache@v3
        with:
          path: ~/.local/bin/poetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Install Poetry
        if: steps.cache_poetry.outputs == ''
        run: |
          curl -sSL https://install.python-poetry.org | python3 -

      - name: Install deps
        run: poetry install

      - name: Run Python script
        run: poetry run python main.py
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_TO: ${{ secrets.TELEGRAM_TO }}
          